<?php

use App\Models\Company;

class GetNullEmployeesCompaniesTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @group ignore
     */
    public function test_取得retry次數小於3的公司()
    {
        $company_data = Company::get_null_employees();
        $this->assertIsArray($company_data);
    }

    /**
     * @group ignore
     */
    public function test_把公司retry次數加1()
    {
        Company::add_retry_times(1);
    }
}
