apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmChart.fullname" . }}
  labels:
    {{- include "helmChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helmChart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helmChart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "helmChart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          env:
          - name: "TEST_CODENAME"
            valueFrom:
              secretKeyRef:
                key:  test_codename
                name: {{ .Chart.Name }}-auth
          - name: "APP_KEY"
            valueFrom:
              secretKeyRef:
                key:  app_key
                name: {{ .Chart.Name }}-auth
          - name: "AWS_CLOUDSEARCH_ENDPOINT"
            valueFrom:
              secretKeyRef:
                key:  aws_cloudsearch_endpoint
                name: {{ .Chart.Name }}-auth
          - name: "AWS_REGION"
            valueFrom:
              secretKeyRef:
                key:  aws_region
                name: {{ .Chart.Name }}-auth
          - name: "AWS_ACCESS_KEY"
            valueFrom:
              secretKeyRef:
                key:  aws_access_key
                name: {{ .Chart.Name }}-auth
          - name: "AWS_SECRET_KEY"
            valueFrom:
              secretKeyRef:
                key:  aws_secret_key
                name: {{ .Chart.Name }}-auth
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
